### ISSUE TITLE
Power button?

### ISSUE THREAD

**Issue by akballow** [bsharper/atv-desktop-remote#17]
Can you share how I can power off the ATV or if not possible please create a power button? Thank you

**Comment by bsharper** [comment]
I turn mine off by pressing L (long presses the TV button), then press the down button and then enter / return. This selects the Power Off button in the Apple TV control center.

**Comment by akballow** [comment]
> I turn mine off by pressing L (long presses the TV button), then press the down button and then enter / return. This selects the Power Off button in the Apple TV control center.

Thanks that solved my issue via keyboard method, but I am guessing there is no way to long press the gui home button? That would be the preferred way.

**Comment by bsharper** [comment]
Good point. I'll try and see if there's a way to add either long-click or possibly right click to trigger a long press instead of a normal press.

Thanks for the feedback.
