### ISSUE TITLE
Long Press function?

### ISSUE THREAD

**Issue by WillyKV** [bsharper/atv-desktop-remote#18]
Hi, thanks allot for ATV Desktop Remote i really like it.

My question is about a possible long press function for buttons on the ATV Remote.

I am trying to acces control center on the Apple TV for things like shutting it off, profile switching or getting into the setting for my airpods.

**Comment by mig8447** [comment]
Long press on the TV button can be achieved when pressing the L key, however, I didn't find a way to long press the enter key

**Comment by bsharper** [comment]
@mig8447 Thanks for providing that information, I've been bad about checking these issues.

Holding shift should send a long press for any key other than TV "t", which has it's own key "L" (lowercase, without shift).
