### ISSUE TITLE
Please add a donate button!

### ISSUE THREAD

**Issue by mkwarman** [bsharper/atv-desktop-remote#24]
I would love to properly thank you for this tool

**Comment by bsharper** [comment]
Thanks for the suggestion! I added the following ko-fi button to the bottom of my README.md:

[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/brianharper)

I do want to make it clear how much this project depends on [pyatv.dev](https://pyatv.dev/), which enables communication to ATVs. Without pyatv this would have stopped working years ago.

**Comment by mkwarman** [comment]
Awesome, thank you. I sent some love to pyatv as well 😄
