### ISSUE TITLE
Modify Shortcut Key

### ISSUE THREAD

**Issue by agrabowski** [bsharper/atv-desktop-remote#25]
This is a great idea! It would solve a lot of problems for my users. 

I was just wondering how hard it would be to modify the keyboard shortcut to activate the menubar item? App development isn't my cup of tea, but I wanted to ask. 

Thanks!

**Comment by bsharper** [comment]
@agrabowski Hi, this is a duplicate of this issue: https://github.com/bsharper/atv-desktop-remote/issues/13#issuecomment-2076119951

I'll try and create a build soon for people to test this out without having to compile it themselves.

**Comment by agrabowski** [comment]
Thanks! Sorry for missing that comment!
