### ISSUE TITLE
Just wanted to say thank you

### ISSUE THREAD

**Issue by Keagel** [bsharper/atv-desktop-remote#5]
Hey!

This is not an issue but I just wanted to say thank you. This is amazing. I have no idea why Apple hasn't implemented it themselves, it makes so much sense: easy keyboard access to search things and the possibility to have intuitive keyboard shortcuts mapped to the remote's keys. Once again someone has to come in and fix what Apple does wrong (or refuses to do). So thank you!

Now for the more 'useful' part. I've been using it for a few days now and haven't encountered a single issue. I'm not sure how much testing you want before you can package this into an installer/app but for what it's worth it works perfectly fine for me on MacOS 12.2.

**Comment by bsharper** [comment]
Thanks for the feedback! You're probably right, at this point should make an installer and make sure people understand what the program does. It really just runs `pip` before it starts to make sure the server has the modules needed to run.

Anyway, thanks again, it's good to hear that it's working for you. I'll try to make a build soon to make it easier for people to try out.
